spring :
  datasource:
    url: jdbc:mysql://localhost:3306/Oasis_Cafe?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: nissa
      password: 123

  mail:
    host: smtp.gmail.com
    port: 587
    username: nisanduab@gmail.com
    password: hesw fonp vqez ziwv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # PayHere Configuration
  payment:
    payhere:
      merchant-id: 1230128
      merchant-secret: ODc2NzI5ODQ4MzE4Mzg2NzUxNjE2NzkyMjA0MjkzMjcyNjc3NTA4
#      return-url: ${PAYHERE_RETURN_URL:http://localhost:4200/order-confirmation}
#      cancel-url: ${PAYHERE_CANCEL_URL:http://localhost:4200/checkout}
      notify-url: https://582b-2402-4000-2281-a2e-d0c6-d4e3-86b7-1cb6.ngrok-free.app
#      auth-code: ${PAYHERE_AUTH_CODE:dummy_auth_code}
      sandbox: true

